services:
  refractory:
    build: .
    ports: 
      - 8080:8080
    volumes:
      - ./foundry_releases_zip:/home/refractory/foundry_releases_zip
      - ./foundry_releases:/home/refractory/foundry_releases
      - ./instance_data:/home/refractory/instance_data
      - ./db:/home/refractory/db
      - update-data:/home/refractory/refractory_data
    environment:
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - DJANGO_SECRET=${DJANGO_SECRET}
volumes:
  update-data:

