services:
  multifoundry:
    build: .
    ports: 
      - 8080:8080
    volumes:
      - release_zips:/app/foundry_releases_zip
      - releases:/app/foundry_releases
      - db:/app/db
volumes:
  releases:
  release_zips:
  db: