[tool.poetry]
name = "multifoundry"
version = "0.1.0"
description = "Foundry VTT Instance Manager"
authors = ["ForOhForError"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.31.0"
twisted = "^22.10.0"
autobahn = {extras = ["twisted"], version = "^23.6.2"}
websockets = "^11.0.3"
django = "^5.0.1"
python-socketio = "^5.11.1"

[tool.poetry.group.dev.dependencies]
beautifulsoup4 = "^4.12.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
