# Generated by Django 5.0.1 on 2024-02-24 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multifoundry_home', '0002_foundryversion_downloaded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundryinstance',
            name='foundry_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='multifoundry_home.foundryversion'),
        ),
    ]
