# Generated by Django 5.0.1 on 2024-02-27 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multifoundry_home', '0003_foundryinstance_foundry_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foundryversion',
            name='downloaded',
        ),
        migrations.AddField(
            model_name='foundryversion',
            name='download_status',
            field=models.CharField(choices=[('Not Downloaded', 'Not Downloaded'), ('Downloading', 'Downloading'), ('Downloaded', 'Downloaded')], default='Not Downloaded', max_length=15),
        ),
        migrations.AlterField(
            model_name='foundrylicense',
            name='instance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foundry_license', to='multifoundry_home.foundryinstance'),
        ),
    ]
