# Generated by Django 5.0.3 on 2024-10-05 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multifoundry_home', '0006_foundrylicense_license_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundryinstance',
            name='display_name',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
