# Generated by Django 5.0.3 on 2024-10-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multifoundry_home', '0007_foundryinstance_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundryinstance',
            name='instance_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
