# Generated by Django 5.0.3 on 2024-10-06 00:27

import django.db.models.deletion
import multifoundry_home.models.foundry_models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multifoundry_home', '0008_alter_foundryinstance_instance_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedFoundryUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=255)),
                ('user_password', models.CharField(default=multifoundry_home.models.foundry_models.generate_default_password, max_length=32)),
                ('world_id', models.CharField(default='', max_length=255)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multifoundry_home.foundryinstance')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
