# Generated by Django 5.0.3 on 2024-10-06 03:48

import multifoundry_home.models.foundry_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multifoundry_home', '0010_managedfoundryuser_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundryinstance',
            name='admin_pass',
            field=models.CharField(default=multifoundry_home.models.foundry_models.generate_default_password, max_length=256),
        ),
        migrations.AlterField(
            model_name='managedfoundryuser',
            name='user_password',
            field=models.CharField(default=multifoundry_home.models.foundry_models.generate_default_password, max_length=64),
        ),
    ]
