# Generated by Django 5.0.3 on 2024-10-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multifoundry_home', '0011_foundryinstance_admin_pass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='managedfoundryuser',
            name='managed_gm',
            field=models.BooleanField(default=False),
        ),
    ]
