# Generated by Django 5.0.3 on 2024-10-10 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multifoundry_home', '0012_managedfoundryuser_managed_gm'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundryinstance',
            name='eula_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
