# Generated by Django 5.0.1 on 2024-02-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refractory_home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundryversion',
            name='downloaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foundryversion',
            name='update_category',
            field=models.CharField(choices=[('Prototype', 'Prototype'), ('Development', 'Development'), ('Testing', 'Testing'), ('Stable', 'Stable')], default='Stable', max_length=15),
        ),
        migrations.AddField(
            model_name='foundryversion',
            name='update_type',
            field=models.CharField(choices=[('Full', 'Full'), ('Update', 'Update')], default='Full', max_length=10),
        ),
    ]
