# Generated by Django 5.1.4 on 2025-09-06 02:11

import django.core.validators
import re
import refractory_home.models.foundry_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("refractory_home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoundryInvite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invite_code",
                    models.CharField(
                        default=refractory_home.models.foundry_models.generate_random_slug,
                        max_length=64,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                re.compile("^[-\\w]+\\Z"),
                                "Enter a valid “slug” consisting of Unicode letters, numbers, underscores, or hyphens.",
                                "invalid",
                            )
                        ],
                    ),
                ),
                ("uses", models.PositiveSmallIntegerField(default=1)),
            ],
        ),
    ]
