# Generated by Django 5.1.4 on 2024-12-20 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("refractory_home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="foundryversion",
            name="build",
            field=models.IntegerField(default=0),
        ),
    ]
