# Generated by Django 5.1.4 on 2025-10-07 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('refractory_home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundryinstance',
            name='access_group',
            field=models.ForeignKey(blank=True, help_text='Group able to log into and register users for the instance; when not set, any user can see the instance.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='auth.group'),
        ),
        migrations.AddField(
            model_name='foundryinstance',
            name='gm_group',
            field=models.ForeignKey(blank=True, help_text='Group able to register GM users for the instance; when not set, only superusers can do so.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='auth.group'),
        ),
        migrations.AddField(
            model_name='foundryinstance',
            name='manage_group',
            field=models.ForeignKey(blank=True, help_text='Group able to access the config page for the instance to install modules/systems and make worlds; when not set, only superusers can do so.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='auth.group'),
        ),
        migrations.AddField(
            model_name='foundryinstance',
            name='view_group',
            field=models.ForeignKey(blank=True, help_text='Group able to view the instance on the front page; when not set, any user can see the instance.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='auth.group'),
        ),
        migrations.AddField(
            model_name='foundryinvite',
            name='assign_user_groups',
            field=models.ManyToManyField(blank=True, help_text='Groups that will be assigned to users generated from this invite', null=True, to='auth.group'),
        ),
    ]
