# Generated by Django 5.1.4 on 2025-10-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("refractory_home", "0002_group_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="managedfoundryuser",
            name="initial_role",
            field=models.IntegerField(choices=[(1, "Player"), (4, "Gm")], default=1),
        ),
        migrations.AlterField(
            model_name="managedfoundryuser",
            name="user_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
