# Generated by Django 5.1.4 on 2025-10-19 20:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("refractory_home", "0003_managedfoundryuser_initial_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foundrylicense",
            name="license_key",
            field=models.CharField(
                max_length=29,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Z1-9]{4}-[A-Z1-9]{4}-[A-Z1-9]{4}-[A-Z1-9]{4}-[A-Z1-9]{4}-[A-Z1-9]{4}$",
                        "Foundry Licenses are of format XXXX-XXXX-XXXX-XXXX-XXXX-XXXX",
                    )
                ],
            ),
        ),
    ]
