# Generated by Django 5.1.4 on 2026-04-16 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("refractory_home", "0004_alter_foundrylicense_license_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="foundryinvite",
            name="invite_name",
            field=models.CharField(default="Invite", max_length=255),
        ),
        migrations.AlterField(
            model_name="foundryinvite",
            name="uses",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Number of uses this invite has remaining. Set to 0 for infinite uses.",
            ),
        ),
        migrations.AlterField(
            model_name="foundryinvite",
            name="assign_user_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Groups that will be assigned to users generated from this invite",
                to="auth.group",
            ),
        ),
    ]
