# Generated by Django 5.0.1 on 2024-02-29 04:28

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refractory_home', '0004_remove_foundryversion_downloaded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundryinstance',
            name='instance_slug',
            field=models.CharField(max_length=30, null=True, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-\\w]+\\Z'), 'Enter a valid “slug” consisting of Unicode letters, numbers, underscores, or hyphens.', 'invalid')]),
        ),
        migrations.AlterField(
            model_name='foundryinstance',
            name='instance_name',
            field=models.CharField(max_length=30),
        ),
    ]
