# Generated by Django 5.0.3 on 2024-09-25 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refractory_home', '0005_foundryinstance_instance_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundrylicense',
            name='license_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
