# Generated by Django 5.0.3 on 2024-10-06 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refractory_home', '0009_managedfoundryuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='managedfoundryuser',
            name='user_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
